language: java
jdk:
- oraclejdk10
matrix:
  include:
  - jdk: openjdk10
    before_install:
    - rm "${JAVA_HOME}/lib/security/cacerts"
    - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    - chmod +x .travis/push-javadoc.sh

    script:
    - mvn javadoc:javadoc
    - mvn test
    after_success:
    - grunt gh-pages:travis
    - ".travis/push-javadoc.sh"
env:
  global:
    secure: pk+GeHXTPBkeuiOOoU6YiIncxeo1C+YL7B1RlqH2mYn5XY0ZeUv9cUsiIFc3G+h5Y+P3zoGqPWhTmiX57Q9b39zXqrEaYYo0nuk5IRdyX2sH4iMWREXHN/juIIKnC4F3tN6dVrbqoMjPtNKG7emM1oh73Mwyh1yOo9I5yAPZSKQuZI3U+RRxmZ4LXre2++IdMsVhQJzTy0KoT5YplnjLnFqgVy57WcBKDBtzFywmPCoGLxZyPnsVN41zxV/25TFj2etpsqm66mDgqZwD/kboQj+W1T1AiwqKTaWgIB+r/hx6JtKn38r/DKJymbVcctaGTu1JFOJvvV6wDYpVfZVzNZ/UrOkYN5GdVAYlC+ZL95z0QK03hbfqYQ+wcAvhz/yW2agsVoByfbZ0i0Ur71V8Kg+9MhjefRnIpJ4uWB5mHa+gQgyVzkXsAO3YdoqgFRelLzusdmKDOGan6xk4BI7s2Asw5eAkrRcWnB9T/V8g22aK5Rk6bJv0eqIXWbuhJDuosP1MG2t34aui1pBA4bYlZjm9RKFBfDYcijVz63rDQqWVzACSvk/AiR4LbhSPfELjWg5gpsG8BlmnzT+nqdA23Pf2wb2IJpE4JGb/SocDuQMYGw6nAXFUZ+HtKwDSYMg8bBiSY5maUWKu6CCFWJ9v0hR6pYQbmddI07fih1+pLb8=
