language: java
jdk:
  - oraclejdk10

matrix:
  include:
  - jdk: openjdk10
    before_install:
    - rm "${JAVA_HOME}/lib/security/cacerts"
    - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    script:
    - mvn javadoc:javadoc
    after_success:
    - javadoc -private -sourcepath "src/main/java:src/main/ressources:src/test/java" pl.put.poznan.scenarioqualitychecker pl.put.poznan.scenarioqualitychecker.scenario pl.put.poznan.scenarioqualitychecker.scenario.dao